# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration
changelog:
  exclude:
    authors:
      - 'dependabot'
  categories:
    - title: 'New'
      labels:
        - 'enhancement'
    - title: 'Fixed'
      labels:
        - 'bug'