name: 'Create Release'

on:
  push:
    tags:
      - 'prerelease-*.*-*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Create Prerelease'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true