name: Tag and Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-tag-and-release:
    if: startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get previous tag
        id: get_previous_tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 || echo "none")
          echo "Previous tag: $PREVIOUS_TAG"
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"

      - name: Create new tag
        id: create_tag
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          VERSION=${BRANCH_NAME#release-}
          echo "Creating new tag: $VERSION"
          git config --global user.email jacky.tung@articulateai.com
          git config --global user.name jackytungArticulateAI
          
          git tag -a "$VERSION" -m "Release $VERSION"
          echo "::set-output name=new_tag::$VERSION"

      - name: Push new tag
        run: |
          git push origin "${{ steps.create_tag.outputs.new_tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CHANGELOG.md
        run: |
          npm install --save-dev conventional-changelog conventional-changelog-cli
          npx conventional-changelog -p angular -i CHANGELOG.md -s --from ${{ steps.get_previous_tag.outputs.previous_tag }} --to ${{ steps.create_tag.outputs.new_tag }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}